// <auto-generated />
namespace Shipwreck.SlackCSharpBot.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTasks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTasks));
        
        string IMigrationMetadata.Id
        {
            get { return "201605271229156_AddTasks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
